### PR TITLE
[config-rewrite] Removing unnecessary configuration caching

### PR DESCRIPTION
**Pull request by nristock**
Quite a few code changes here. I removed the additional configuration caching through Config and IRCd classes and added getter and setter methods to the Config class which query the underlying FileConfiguration directly.
Since I had to do a lot of manual code changes I'd really appreciate if you actually look on the code before merging it.

### CODE REVIEW

**Comment by WizardCM** [comment]
So I did a small initial test the other day from your branch, and this is what I was able to gather.
- The plugin doesn't seem to actually read the configuration file in the folder, as when loading it on my server it completely ignored the fact that my config file tells it to run in linking mode - instead it sat there in standalone mode.
- However, it does say in console that it loaded the config file fine so... I dunno.

**Comment by nristock** [comment]
Seemed to work fine when I tested.... I gonna check again, though. Thanks.

**Comment by WizardCM** [comment]
Any luck with this @monofraps? Would love to merge this into development relatively soon.

**Comment by nristock** [comment]
Oh crap. I completey forgot about this, sorry.
I'll look into it now.

**Comment by nristock** [comment]
Gosh. I finally found the issue. Doing some more tests. - Code should be up within the next 24 hours.

**Comment by WizardCM** [comment]
I can totally understand why it took a while, the original code is such a mess. Kind of the reason behind the rewrite. :P

**Pull request merged**
