### PR TITLE
Clean up repository 

### PR DESCRIPTION
**Pull request by chyyran**
Just cleaned up unneeded files, cleaned up Readme.md, added License.md, that sort of stuff.

Also, don't forget to register add BukkitIRCd to PluginMetrics at [MCStats.org](http://mcstats.org/plugin/BukkitIRCd).

Note: Not exactly sure why my name shows up on the signature at MCStats.org.

### CODE REVIEW

**Comment by WizardCM** [comment]
Already registered BukkitIRCd on PluginMetrics and got the approval email, so all good on that front.

**Comment by WizardCM** [comment]
Also, TravicCI may not have worked because it's disabled on my end (both the hook in GitHub and on my TravisCI account). If you want, I can enable it as a test.

**Comment by chyyran** [comment]
It's per-repository, so having it disabled on your end won't change it. It just gets stuck and won't build, here's the result of my test: https://travis-ci.org/ron975/BukkitIRCd

**Comment by WizardCM** [comment]
Basically it's not downloading dependencies.. I wonder if there's a way to disable that line and run a custom one. (ie. mvn clean install)

Edit: Done and fixed
https://travis-ci.org/WMCAlliance/BukkitIRCd
Any idea how to limit version downloads for dependencies? No need for it to download all the old builds of Bukkit, is there?

**Pull request merged**
